version: '3.5'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: giggio/openvpn-arm
    container_name: openvpn
    ports:
     - "1194:1194"
    restart: always
    volumes:
     - ./config:/etc/openvpn
