version: '3.5'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: giggio/openvpn-arm
    container_name: openvpn
    ports:
     - "1194:1194"
    restart: always
    volumes:
     - ./config:/etc/openvpn
    networks:
      vpn_net:
        ipv4_address: 172.99.0.2
  expect-telnet:
    build:
      context: ./docker/expect-telnet
    environment:
      ROUTER_ADDRESS: "${ROUTER_ADDRESS}"
      ROUTER_USERNAME: "${ROUTER_USERNAME}"
      ROUTER_PASSWORD: "${ROUTER_PASSWORD}"
    networks:
      vpn_net:
        ipv4_address: 172.99.0.3
networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/24
          gateway: 172.99.0.1
